### ISSUE TITLE
Error when working and not forked worker

### ISSUE THREAD

**Issue by goffyara** [Inpassor/yii2-daemon#3]
v.0.3.1

config
```php
'daemon' => [
            'class' => 'inpassor\daemon\Controller',
            'uid' => 'daemon',
            'pidDir' => '@runtime/daemon', // PID file directory.
            'logsDir' => '@runtime/logs', // Log files directory.
            'clearLogs' => false, // Clear log files on start.
            'workersMap' => [
                'watcher' => [
                    'class' => 'inpassor\daemon\workers\Watcher',
                    'active' => true, // If set to false, worker is disabled.
                    'maxProcesses' => 1, // The number of maximum processes of the daemon worker running at once.
                    'delay' => 10, // The time, in seconds, the timer should delay in between executions of the daemon worker.
                ],
                'MyWorker' => [
                    'class' => 'console\workers\MyWorker',
                    'active' => true, // If set to false, worker is disabled.
                    'maxProcesses' => 6, // The number of maximum processes of the daemon worker running at once.
                    'delay' => 5, // The time, in seconds, the timer should delay in between executions of the daemon worker.
                ],
            ],
        ],
```

MyWorker.php
```php
<?php
namespace console\workers;

use inpassor\daemon\Worker;

class MyWorker extends Worker
{
    public function run()
    {
        $this->log('ok ---> ' . uniqid());
    }

}
```

```bash
$ php5.6 ./vendor/inpassor/yii2-daemon/yiid start

#!/usr/bin/env php
Starting Yii 2 Daemon 0.3.1... OK.
```
end exit... (if systemd it don't started too)

Error every 5 sec
```
PHP Fatal error:  Uncaught exception 'yii\base\ErrorException' with message 'fwrite(): 3 is not a valid stream resource' in /data/sites/crm/vendor/yiisoft/yii2/helpers/BaseConsole.php:720
Stack trace:
#0 /data/sites/crm/vendor/yiisoft/yii2/console/ErrorHandler.php(64): yii\helpers\BaseConsole::stderr()
#1 /data/sites/crm/vendor/yiisoft/yii2/base/ErrorHandler.php(259): yii\console\ErrorHandler->renderException()
#2 /data/sites/crm/vendor/yiisoft/yii2/base/ErrorHandler.php(0): yii\base\ErrorHandler->handleFatalError()
#3 /data/sites/crm/vendor/inpassor/yii2-daemon/yiid(21): ::unknown()
#4 {main}
  thrown in /data/sites/crm/vendor/yiisoft/yii2/helpers/BaseConsole.php on line 720
[18-Apr-2017 17:53:57 Etc/GMT-3] PHP Stack trace:
[18-Apr-2017 17:53:57 Etc/GMT-3] PHP   1. {main}() /data/sites/crm/vendor/inpassor/yii2-daemon/yiid:0
[18-Apr-2017 17:53:57 Etc/GMT-3] PHP   2. require() /data/sites/crm/vendor/inpassor/yii2-daemon/yiid:21
```

```bash
ps -ax|grep 'yiid'
24464 ?        Ss     0:00 php5.6 ./vendor/inpassor/yii2-daemon/yiid start
24489 pts/0    S+     0:00 grep --color=auto yiid
```

**Comment by Inpassor** [comment]
Thank you for your report.
This situation occurs when an incorrect I/O redirection occurs in the Worker's method log().

Please check out the new release 0.3.2:
[https://github.com/Inpassor/yii2-daemon/releases/tag/0.3.2](https://github.com/Inpassor/yii2-daemon/releases/tag/0.3.2)

**Comment by goffyara** [comment]
It's helped. But start only one process, no forks.  It seems the watcher stops...

**Comment by Inpassor** [comment]
Now I will try to reproduce the problem ...

**Comment by Inpassor** [comment]
Are you sure that the watcher stops? It has 1 minute interval.
The interval indicates how often the worker process will be started. If the running time of the process is less than the interval, then in any case there will be only one process in memory.
In case the script runtime is longer than the interval, a fork of the process will be started.
Any worker have individual interval and the number of max forks.

**Comment by goffyara** [comment]
Thx. I expected to see 6 at the same time...
